# -*- coding: utf-8 -*-
"""deconstruct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1he-5V1AUIJuzXC42WuF4NzfCNdlkKXyz
"""

!pip install pytesseract

import cv2
import numpy as np
import pytesseract
import os
from matplotlib import pyplot as plt

def process_document(image_path):
    # 1. Read Image
    print(f"[*] Loading image: {image_path}")
    image = cv2.imread(image_path)
    if image is None:
        print("[!] Error: Image not found. Please check the path.")
        return

    original = image.copy()

    # 2. Image Processing
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)

    # 3. Edge Detection
    edges = cv2.Canny(blur, 50, 150)

    # 4. Morphological Operations
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 5))
    dilated = cv2.dilate(edges, kernel, iterations=3)

    # 5. Contour Detection
    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    print(f"[*] Found {len(contours)} potential elements. Analyzing...")

    # Create output directory
    os.makedirs('output', exist_ok=True)

    text_count = 0
    figure_count = 0

    # 6. Classification
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)

        if w > 50 and h > 20:
            roi = original[y:y+h, x:x+w]

            extracted_text = pytesseract.image_to_string(roi, config='--psm 6').strip()

            if len(extracted_text) > 3:
                label = "Text"
                color = (0, 255, 0)
                text_count += 1
            else:
                label = "Figure/Diagram"
                color = (0, 0, 255)
                figure_count += 1

            cv2.rectangle(image, (x, y), (x+w, y+h), color, 2)
            cv2.putText(image, label, (x, y - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    # Save output
    output_filename = os.path.join('output', 'analyzed_' + os.path.basename(image_path))
    cv2.imwrite(output_filename, image)

    print("-" * 30)
    print("[*] Processing Complete!")
    print(f"[*] Found {text_count} Text Blocks and {figure_count} Figures/Diagrams.")
    print(f"[*] Annotated image saved to: {output_filename}")
    print("-" * 30)

    # ✅ DISPLAY IMAGE
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title("Output Image")
    plt.axis("off")
    plt.show()


# Direct call
image_path = "sample.jpg"
process_document(image_path)

